<a href="https://colab.research.google.com/github/waheddevs/ai_foundation/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import pandas as pd

In [ ]:

mydataset = {
  'cars': ["BMW", "Volvo", "Ford", "Tesla", "Ferrari", "Ford", "BMW"],
  'counts': [3, 7, 2, 8, 1, 9, 3]
}

df = pd.DataFrame(mydataset)

print(df)

      cars  counts
0      BMW       3
1    Volvo       7
2     Ford       2
3    Tesla       8
4  Ferrari       1
5     Ford       9
6      BMW       3

In [ ]:
df.head() # default 5 rows

      cars  counts
0      BMW       3
1    Volvo       7
2     Ford       2
3    Tesla       8
4  Ferrari       1

In [ ]:
df.tail() # default 5 rows

      cars  counts
2     Ford       2
3    Tesla       8
4  Ferrari       1
5     Ford       9
6      BMW       3

In [ ]:
df.shape()

In [ ]:
df.columns

Index(['cars', 'counts'], dtype='object')

In [ ]:
df.dtypes

cars      object
counts     int64
dtype: object

In [ ]:
df.describe(include="all") # numerical columns only

In [ ]:
df.iloc[-1]

In [ ]:
df.loc[1, "cars"]

'Volvo'

In [ ]:
df[df["cars"] == "BMW"]

  cars  counts
0  BMW       3
6  BMW       3

In [ ]:
# df.mean(numeric_only=True)

counts    4.714286
dtype: float64

In [ ]:
df.sum()

cars      BMWVolvoFordTeslaFerrariFordBMW
counts                                 33
dtype: object

In [ ]:
df.min()

In [ ]:
df.max()

In [ ]:
df.median(numeric_only=True)

In [ ]:
df.count()

In [ ]:
df.std(numeric_only=True)

In [ ]:
data_with_missing = {
    "cars": ["BMW", "Volvo", None, "Tesla", "Ferrari", None, "Ford"],
    "counts": [3, 7, None, 8, 1, 9, None],
}
df_missing = pd.DataFrame(data_with_missing)

print(df_missing)

      cars  counts
0      BMW     3.0
1    Volvo     7.0
2     None     NaN
3    Tesla     8.0
4  Ferrari     1.0
5     None     9.0
6     Ford     NaN

In [ ]:
df_missing.isnull().sum()

cars      2
counts    2
dtype: int64

In [ ]:
df_missing.dropna()

      cars  counts
0      BMW     3.0
1    Volvo     7.0
3    Tesla     8.0
4  Ferrari     1.0

In [ ]:
df_missing.fillna({"cars": "unknown", "counts": 0})

      cars  counts
0      BMW     3.0
1    Volvo     7.0
2  unknown     0.0
3    Tesla     8.0
4  Ferrari     1.0
5  unknown     9.0
6     Ford     0.0

In [ ]:
df = pd.read_csv("Titanic-Dataset.csv")

df.tail()

# df = pd.read_excel("Titanic-Dataset.xlsx")
# df = pd.read_json("Titanic-Dataset.json")

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,0,3,"Shorney, Mr. Charles Joseph",male,NaN,0,0,374910,8.0500,NaN,S
96,97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C
97,98,1,1,"Greenfield, Mr. William Bertram",male,23.0,0,1,PC 17759,63.3583,D10 D12,C
98,99,1,2,"Doling, Mrs. John T (Ada Julia Bone)",female,34.0,0,1,231919,23.0000,NaN,S
99,100,0,2,"Kantor, Mr. Sinai",male,34.0,1,0,244367,26.0000,NaN,S

In [ ]:
df.to_excel("test.xlsx")

In [ ]:
# Series => 1D
cars = pd.Series(["BMW", "Tesla", "Ferrari"])
print(cars)

0        BMW
1      Tesla
2    Ferrari
dtype: object

In [ ]:
cars_series = data_with_missing['cars']
print(cars_series)

['BMW', 'Volvo', None, 'Tesla', 'Ferrari', None, 'Ford']